import React, { Component } from 'react';
import './info.css';
import {Icon} from 'react-fa'

class Info extends Component {
    render() {
        return (
            
            <div id="info" className="info">
                
                <div class="flex-container">
                    <div className="speechRec">SPEECH RECOGNITION
                        <p></p>
                       <Icon className ="icons" name="microphone" size="2x"/>
                      <p>State of the art voice recognition to understand the setting of the conversation.</p>
                    </div>
                    <div>LANGUAGE PROCESSING
                        <p></p>
                       <Icon className ="icons" name="language" size="2x"/>
                     <p>Interpreting conversations & extracting segments into clinical notes.</p>
                    </div>
                    <div>MACHINE LEARNING
                        <p></p>
                       <Icon className ="icons" name="line-chart" size="2x"/>
                    <p>Using AI algorithms to personalise content over time.</p>
                    </div>

                </div>
                <div class="flex-container2">
                    <div>SEAMLESS INTEGRATION
                        <p></p>
                       <Icon className ="icons" name="plug" size="2x"/>
                    <p>An effortless switch to increase efficiency & convenience.</p>
                    </div>
                    <div>REAL TIME
                        <p></p>
                       <Icon className ="icons" name="clock-o" size="2x"/>
                    <p>The notes will be generated by the end of each consultation.</p>
                    </div>

                    <div>CONTEXT UNDERSTANDING
                        <p></p>
                       <Icon className ="icons" name="puzzle-piece" size="2x"/>
                    <p>Our smart AI can grasp different forms of language.</p>
                    </div>
                </div>
            </div>

        );
    }
}

export default Info;